WINDOW_TITLE = "SUPERMARIO (LITE)"
FPS = 60
TILEMAP_TILE_SIZE = 16
TILE_SIZE = 32
WINDOW_WIDTH = TILE_SIZE * 22
WINDOW_HEIGHT = TILE_SIZE * 18

LEVEL_BG_COLOR = (131, 197, 247)

__GITHUB_URL__ = "https://github.com/BALARISHITHBALLI"
__GITHUB_CODE_URL__ = "https://github.com/BALARISHITHBALLI/CS-Platformer-Game"

__MENU_MESSAGE__ = "MADE BY RUDRA-RAM"
LINK_COLOR = LEVEL_BG_COLOR
